#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install everything else
brew install ack
brew install autojump
brew install ctags
brew install git
brew install git-flow
brew install git-multipush
brew install htop-osx
brew install iftop
brew install nmap
brew install ntfs-3g # Tuxera community version
brew install mtr
brew install pbzip2
brew install python
brew install s3cmd
brew install ssh-copy-id
brew install tree
brew install watch
brew install webkit2png
brew install wkhtmltopdf
brew install wget --enable-iri
brew install zsh

# Web development
brew install phantomjs
brew install node
brew install postgres
brew install redis
brew install mysql

# enable head-only formulae (like otx)
brew tap homebrew/headonly

# Reversing
brew install otx --HEAD
brew install class-dump

brew install youtube-dl
brew install rtmpdump

# R
brew install gfortran
brew install r

# Octave
brew install octave

# OpenCV and SimpleCV (http://www.simplecv.org/docs/installation.html)
brew install opencv
brew install sdl sdl_image sdl_mixer sdl_ttf portmidi
brew install smpeg --HEAD

# brew install readline
# rvm reinstall 1.9.3 --with-readline-dir=/usr/local/Cellar/readline/6.2.4

# Remove outdated versions from the cellar
brew cleanup
