#!/bin/bash

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# enable head-only formulae (like otx)
brew tap homebrew/headonly
brew tap homebrew/science

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils

brew install moreutils --without-parallel

echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils

# Install everything else
brew install ag # ack
brew install astyle
brew install autojump
brew install axel # wget with auto-resume and multiple connections
brew install bazaar
#brew install class-dump # requires XCode 
brew install ctags
brew install curl
brew install cv --HEAD  # coreutils viewer (monitor performance of coreutils)
brew install djvu2pdf
brew install doxygen
brew install ffmpeg --with-fdk-aac --with-ffplay --with-freetype --with-frei0r --with-libass --with-libvo-aacenc --with-libvorbis --with-libvpx --with-opencore-amr --with-openjpeg --with-opus --with-rtmpdump --with-schroedinger --with-speex --with-theora --with-tools
brew install figlet
brew install gcal
brew install gcc
brew install gist
brew install git
brew install git-extras
brew install git-flow
brew install git-multipush
brew install gnupg
brew install gnuplot
brew install go
brew install graphicsmagick # instead of imagemagick 
brew install graphviz
brew install htop-osx
brew install icdiff
brew install iftop
#brew install imagesnap # requires XCode
brew install innotop
brew install jq # json sed
brew install latex-mk
brew install laurent22/massren/massren
brew install maven
brew install mercurial
brew install moreutils
brew install mtr
brew install nmap
brew install node
#brew install otx --HEAD # full XCode required
brew install parallel --force
brew install pbzip2
brew install peco # interactive grep
brew install percona-server # mysql
brew install phantomjs
brew install postgresql
brew install pup  # like html grep
# brew install pyenv
# brew install pypy
brew install q # sql on csv (github.com/harelba/q)
brew install r
brew install ranger
brew install readline
brew install redis
brew install rename
brew install rlwrap
brew install rtmpdump
brew install sl
brew install spark # ▁▂▃▅▂▇ in your shell
brew install sqlite
brew install ssh-copy-id
brew install homebrew/dupes/tidy
brew install tig
brew install tmux
brew install tree
brew install unrar
brew install watch
brew install webkit2png
brew install wget --with-iri
brew install youtube-dl
brew install zsh
brew install zsh-syntax-highlighting

# OpenCV and SimpleCV (http://www.simplecv.org/docs/installation.html)
#brew install opencv
#brew install sdl sdl_image sdl_mixer sdl_ttf portmidi
#brew install smpeg --HEAD

# brew install readline
# rvm reinstall 1.9.3 --with-readline-dir=/usr/local/Cellar/readline/6.2.4

# Remove outdated versions from the cellar
brew cleanup

