set guifont=BitstreamVeraSansMono-Roman:h13            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark               " Background.
set lines=38 columns=130          " Window dimensions.
"set guioptions-=r                 " Don't show right scrollbar
set go-=L                         " Hide the left scrollbar

" Using Command+t for CommandT
macmenu &File.New\ Tab key=<D-T>
map <D-t> :CommandT<CR>

" Command-Return for fullscreen
macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>

" Command-][ to increase/decrease indentation
vmap <D-]> >gv
vmap <D-[> <gv

" Command-Shift-F for Ack
map <D-F> :Ack<space>

" persistent undos - undo after you re-open the file
" but this gives warnings under command line vim
" use only in macvim
set undodir=~/.vim/backups
set undofile

" Open Command+T in a new tab
"let g:CommandTAcceptSelectionTabMap='<CR>'

" C-TAB and C-SHIFT-TAB cycle tabs forward and backward
nmap <c-tab> :tabnext<cr>
imap <c-tab> <c-o>:tabnext<cr>
vmap <c-tab> <c-o>:tabnext<cr>
nmap <c-s-tab> :tabprevious<cr>
imap <c-s-tab> <c-o>:tabprevious<cr>
vmap <c-s-tab> <c-o>:tabprevious<cr>

" C-# switches to tab
nmap <d-1> 1gt
nmap <d-2> 2gt
nmap <d-3> 3gt
nmap <d-4> 4gt
nmap <d-5> 5gt
nmap <d-6> 6gt
nmap <d-7> 7gt
nmap <d-8> 8gt
nmap <d-9> 9gt

" Disable Middle Click
nnoremap <MiddleMouse> <Nop>
nnoremap <2-MiddleMouse> <Nop>
nnoremap <3-MiddleMouse> <Nop>
nnoremap <4-MiddleMouse> <Nop>

inoremap <MiddleMouse> <Nop>
inoremap <2-MiddleMouse> <Nop>
inoremap <3-MiddleMouse> <Nop>
inoremap <4-MiddleMouse> <Nop>

" Disable the MacVim contextual menu in order to use it for taglist navigation
" defaults write org.vim.MacVim MMTranslateCtrlClick 0

" Showing tab label as: "[1] .vimrc [+]"
set guitablabel=[%N]\ %f\ :%m

