set guifont=Monaco:h14            " Font family and font size.
set antialias                     " MacVim: smooth fonts.
set encoding=utf-8                " Use UTF-8 everywhere.
set guioptions-=T                 " Hide toolbar.
set background=dark               " Background.
set lines=38 columns=130          " Window dimensions.
set guioptions-=r                 " Don't show right scrollbar
set go-=L                         " Hide the left scrollbar

"colorscheme solarized
colorscheme railscasts

" Using Command+t for fuzzyfinder
macmenu &File.New\ Tab key=<D-T>
map <D-t> :call fuf#givenfile#launch('', 0, '> ', split(glob('./**/*'), "\n"))<CR>

" Command-Return for fullscreen
macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>

" Command-/ to toggle comments
map <D-/> <plug>NERDCommenterToggle<CR>
imap <D-/> <Esc><plug>NERDCommenterToggle<CR>i

" Command-][ to increase/decrease indentation
vmap <D-]> >gv
vmap <D-[> <gv

" Command-Shift-F for Ack
map <D-F> :Ack<space>
